$(document).ready(function(){
    $('#design-fig').click(function(){
        $('#design').toggle();
        $('#design-icon').toggle();
    })
    $('#dev-fig').click(function(){
        $('#development').toggle();
        $('#dev-icon').toggle();
    })
    $('#products-fig').click(function(){
        $('#product').toggle();
        $('#products-icon').toggle();
    })
})